# Default configuration
random_seed: 42

# PCA
pca:
  n_components: 500
  whiten: false

# Models
xgboost:
  n_estimators: 400
  learning_rate: 0.05
  max_depth: 6
  subsample: 0.9
  colsample_bytree: 0.8
  reg_lambda: 1.0
  objective: "multi:softprob"

lightgbm:
  n_estimators: 500
  learning_rate: 0.05
  max_depth: -1
  num_leaves: 64
  subsample: 0.9
  colsample_bytree: 0.8
  reg_lambda: 1.0
  objective: "multiclass"

# Binary tasks
binary:
  positive_class: "BRCA"  # used only for one-vs-rest
